apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: results
  name: results
spec:
  ports:
  - name: 80-30100
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30100
  selector:
    role: results
  type: NodePort
