apiVersion: v1
kind: ReplicationController
metadata:
  name: vote
spec:
  minReadySeconds: 20
  replicas: 4
  selector:
    role: vote
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
        - name: app
          image: initcron/oc-vote:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"

