apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote
spec:
  maxReplicas: 15
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: vote
  targetCPUUtilizationPercentage: 60
